name: ytquran
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  scrollable_positioned_list: ^0.2.3
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.15
  share_plus: ^4.0.3
  simple_gradient_text: ^1.2.4
  url_launcher: ^6.1.6
  flutter_qiblah: ^2.1.0
  location: ^4.4.0







  conditional_builder_null_safety: ^0.0.6
  percent_indicator: ^4.2.2
  flutter_screenutil: ^5.5.3+2
  flutter_offline: ^2.1.0
  lottie: ^1.3.0
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.1+1
  arabic_numbers: ^1.0.0
  analog_clock: ^0.1.1
  device_info_plus: ^4.0.1
  flutter_launcher_icons: ^0.10.0
  vibration: ^1.7.5







dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/quran.png
  android: true
  ios: true
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: quran
      fonts:
        - asset: assets/HafsSmart_08.ttf
    - family: me_quran
      fonts:
        - asset: assets/me_quran.ttf
